/* exp3_5_interrupt_version.c
   EE470 - Experiment 3.5 modified with interrupts only
   Frequency measurement using TC0 (external counter on T0/PD4)
   1-second gate time generated by TC2 Compare Match A interrupt in CTC mode
*/

#include "ee470avr.h"
#include <stdio.h>

volatile uint32_t total_pulses = 0;      
volatile uint8_t  update_freq = 0;       

ISR(TIMER0_OVF_vect)
{
    total_pulses += 256;                 
}

ISR(TIMER2_COMPA_vect)
{
    static uint8_t ticks = 0;
    ticks++;

    // 125 interrupts × 125 ticks each = 15625 timer ticks = exactly 1 second
    if (ticks >= 125) {
        total_pulses += TCNT0;
        TCNT0 = 0;
        update_freq = 1;
        ticks = 0;
    }
}

int main(void)
{
    char line[80];

    bitclr(DDRD, PD4); // T0 input

    serial_init(103); // 9600 @ 16 MHz
    putstr("\r\nFrequency Meter (Interrupt-Driven)\r\n");

    TCCR0A = 0x00;
    TCCR0B = 0b111;          
    TCNT0 = 0;
    bitset(TIMSK0, TOIE0);

    TCCR2A = (1 << WGM21);   // CTC
    TCCR2B = 0b111;           // Prescaler 1024
    OCR2A = 124;             
    bitset(TIMSK2, OCIE2A);

    sei();

    while(1)
    {
        if(update_freq)
        {
            uint32_t pulses = total_pulses;
            total_pulses = 0;
            update_freq = 0;

            sprintf(line, "Frequency = %lu Hz\r\n", pulses);
            putstr(line);
        }
    }
}
